name: Generate Project Maven Modules

on:
  release:
    types: [ created ]

jobs:
  generate-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r replicate-tools/requirements.txt

      - name: Run replicate-tools to download JSON schemas
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          cd replicate-tools
          python download_replicate_schemas.py

      - name: Run Maven to generate modules & Deploy Maven artifacts to GitHub Packages
        env:
          VERSION: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B -ntp versions:set -DnewVersion=$VERSION
          mvn -B -ntp clean install
          mvn -B -ntp deploy -pl '!replicate-models'
